# -*- coding: utf-8 -*-
"""Library Management System

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VeDIxrrjrsd4KW-3W1lKydh8xhWzmeCJ
"""

class Library:
    def __init__(self):
        # Open the books.txt file with "a+" mode
        self.file_path = "books.txt"
        self.file = open(self.file_path, "a+")
        print("Library opened")

    def __del__(self):
        # Close the file in the destructor method
        self.file.close()
        print("Library closed")

    def list_books(self):
        # List all books in the books.txt file
        self.file.seek(0)  # Move the file cursor to the beginning
        book_lines = self.file.read().splitlines()

        for line in book_lines:
            title, author, release_year, num_pages = line.split(',')
            print(f"Title: {title}, Author: {author}, Release Year: {release_year}, Pages: {num_pages}")

    def add_book(self):
        # Add a book to the books.txt file
        title = input("Enter book title: ")
        author = input("Enter book author: ")
        release_year = input("Enter release year: ")
        num_pages = input("Enter number of pages: ")

        book_info = f"{title},{author},{release_year},{num_pages}\n"
        self.file.write(book_info)
        print("Book added successfully!")

    def remove_book(self):
        # Remove a book from the books.txt file
        title_to_remove = input("Enter the title of the book to remove: ")

        # Read the file contents and add books to a list
        self.file.seek(0)
        book_lines = self.file.read().splitlines()

        # Find the index of the book to be deleted in the list
        index_to_remove = -1
        for i, line in enumerate(book_lines):
            if title_to_remove in line:
                index_to_remove = i
                break

        # Remove the book from the list
        if index_to_remove != -1:
            del book_lines[index_to_remove]

            # Remove the contents of the books.txt
            self.file.seek(0)
            self.file.truncate()

            # Add all elements of the list to the books.txt
            for line in book_lines:
                self.file.write(line + '\n')

            print("Book removed successfully!")
        else:
            print("Book not found in the library.")
# Create an object named “lib” with “Library” class
lib = Library()

# Create a menu to interact with the “lib” object
while True:
    print("*** MENU ***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("4) Quit")

    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        lib.list_books()
    elif choice == '2':
        lib.add_book()
    elif choice == '3':
        lib.remove_book()
    elif choice == '4':
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 4.")

from google.colab import drive
drive.mount('/content/drive')



"""# New Section"""